spring:
  application:
    name: API Iudigital
# conexión a base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/iudigital
    username: root
    password:
# jpa properties
  jpa:
    hibernate:
      ddl-auto: create-drop